["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "./lib"

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
AstralyFaucet = [
    "contracts/AstralyFaucet.cairo",
]
AstralyINOContract = [
    "contracts/AstralyINOContract.cairo",
]
AstralyIDOContract = [
    "contracts/AstralyIDOContract.cairo",
]
AstralyIDOFactory = [
    "contracts/AstralyIDOFactory.cairo",
]
