["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "./lib"

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
AstralyINOContract = [
    "contracts/IDO/AstralyINOContract.cairo",
]
AstralyINOContractMock = [
    "contracts/mocks/AstralyINOContract_mock.cairo",
]
AstralyIDOContract = [
    "contracts/IDO/AstralyIDOContract.cairo",
]
AstralyIDOContractMock = [
    "contracts/mocks/AstralyIDOContract_mock.cairo",
]
AstralyIDOFactory = [
    "contracts/IDO/AstralyIDOFactory.cairo",
]
Xoroshiro = [
    "contracts/utils/xoroshiro128_starstar.cairo",
]
Referral = [
    "contracts/Referral/AstralyReferral.cairo",
]
