["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "./lib"

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
AstralyINOContract = [
    "contracts/AstralyINOContract.cairo",
]
AstralyINOContractMock = [
    "contracts/mocks/AstralyINOContract_mock.cairo",
]
AstralyIDOContract = [
    "contracts/AstralyIDOContract.cairo",
]
AstralyIDOFactory = [
    "contracts/AstralyIDOFactory.cairo",
]
