name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.13
      - name: Install dependencies
        run: |
          python3.8 -m pip install --upgrade pip
          pip install poetry
          if [ -f pyproject.toml ]; then poetry install; fi
      - name: Test with pytest
        run: |
          poetry run pytest tests/
